* pyNMR
pyNMR is mainly a python module to import nmr Data as generated by Bruker, TecMag and Chemagnetics Consoles.


** Core functionality
It provides a few basic routines for Fourier Transform. It is typically used in a IPython Notebook to interactively analyze NMR Data.

The data are stored in the allFid array. After import, the first FID of a 2D dataset (or the FID of a 1D dataset, for that matter) is stored in
nmrData.allFid[0]

When processing nmrData, the new data maybe stored at a position incremented by 1, using the `fromPos` and `toPos` attributes of the various functions. 

A typical set of processing commands is

#+BEGIN_SRC python
import nmrDataMod as ndm

data = ndm.nmrData(pathToData, "TopSpin")
data.leftShift(0, 1, 70)
data.lineBroadening(1, 2, 5)
data.fourierTransform(2, 3)
data.phase(3, 4, 45, degree = True)
#+END_SRC


Various functions exist to set a chemical shift scale or calculate integrals for all spectra in a 2D dataset.
 

** Further routines
gammaList.py provides a table with the gamma values of the various nuclei. 

fitMod.py may be used to fit nmr data interactively and includes simple models to fit data from a few very basic NMR experiments.

fwhm.py allows to calculate the full with at half maximum of a spectrum

polarization.py provides a routine to calculate thermal polarization as function of nucleus, field and temperature.

nutation.py implements a formula to estimate the \pi/2 pulse by specifying coil volume, circuit Q, Larmor frequency and RF power.
